spring.application.name=api

spring.datasource.url=jdbc:postgresql://localhost:5433/eco_db
spring.datasource.username=eco_user
spring.datasource.password=eco_pass

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true

