spring.application.name=api

# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5433/eco_db
spring.datasource.username=eco_user
spring.datasource.password=eco_pass

# Hibernate
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true

# JWT
app.jwt.secret=miSuperClaveJWTultraSegura12345678346445heffwwf2345654yhegrds2r33554uyrgdfw23r90!
app.jwt.expiration-ms=86400000

# CORS
app.cors.allowed-origins=http://localhost:5173
